language: c
os: linux
compiler: gcc
script:
  - make clean
  - make

matrix:
  include:
    # Linux
    - compiler: gcc
      script:
        - make clean
        - make deb
    # Win32
    - compiler: i686-w64-mingw32-gcc
      addons:
        apt:
          packages:
            - gcc-mingw-w64-base
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
      script:
        - make clean
        - make zip
    # Win64
    - compiler: x86_64-w64-mingw32-gcc
      addons:
        apt:
          packages:
            - gcc-mingw-w64-base
            - binutils-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
      script:
        - make clean
        - make zip

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Wx9oq+Cxi26u6IhJRtSbM0QemO4q92Ysz5j0EnQzpR5V+quIDPgsQA8jodUYW17x74hB6XpmQu1OpdstZnPPfZsBUnLSRD7SeMRt2Nicm+FM1QbTUBE7qWSm+mRT1CYjya9H+6qf0r/fYMs3Cnh+XYOJ4/l/FSO9SdsEJJmTkBk="

addons:
  coverity_scan:
    project:
      name: "msalau/rl78flash"
      description: "Build submitted via Travis CI"
    notification_email: maksim.salau@gmail.com
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: coverity_scan

deploy:
  provider: releases
  api_key:
    secure: kESi7jtWoN0zauhYOnQ+Td9fo6naGA7v9S9u1DKQQL8OuXNZz150ytp3G13GsqBFKQYfksnmP7sKfWGlJnC4tEQ8axBRD913gW24rkgySL9CuhCXGuv+yaPRjYzVfgt0NFpCqes3boz+wCOjez55ZXY5F8oWFEpzp+4OGQCvVoQ=
  file_glob: true
  file:
    - rl78flash-*.zip
    - rl78flash_*.deb
  skip_cleanup: true
  on:
    repo: msalau/rl78flash
    tags: true
